 // Helper code to parse the string with all the fruits
//  const parsed5 = string.split('\n').map(fruit => fruit.replace(/(\d){1,3}-/, ''))
const fruits = [
    'kiwi',
    'pear',
    'kiwi',
    'banana',
    'melon',
    'banana',
    'melon',
    'pineapple',
    'apple',
    'pineapple',
    'cucumber',
    'pineapple',
    'cucumber',
    'orange',
    'grape',
    'orange',
    'grape',
    'apple',
    'grape',
    'cherry',
    'pear',
    'cherry',
    'pear',
    'kiwi',
    'banana',
    'kiwi',
    'apple',
    'melon',
    'banana',
    'melon',
    'pineapple',
    'melon',
    'pineapple',
    'cucumber',
    'orange',
    'apple',
    'orange',
    'grape',
    'orange',
    'grape',
    'cherry',
    'pear',
    'cherry',
    'pear',
    'apple',
    'pear',
    'kiwi',
    'banana',
    'kiwi',
    'banana',
    'melon',
    'pineapple',
    'melon',
    'apple',
    'cucumber',
    'pineapple',
    'cucumber',
    'orange',
    'cucumber',
    'orange',
    'grape',
    'cherry',
    'apple',
    'cherry',
    'pear',
    'cherry',
    'pear',
    'kiwi',
    'pear',
    'kiwi',
    'banana',
    'apple',
    'banana',
    'melon',
    'pineapple',
    'melon',
    'pineapple',
    'cucumber',
    'pineapple',
    'cucumber',
    'apple',
    'grape',
    'orange',
    'grape',
    'cherry',
    'grape',
    'cherry',
    'pear',
    'cherry',
    'apple',
    'kiwi',
    'banana',
    'kiwi',
    'banana',
    'melon',
    'banana',
    'melon',
    'pineapple',
    'apple',
    'pineapple',
  ]
  function SubtractSum(n) {
    let num =
      n -
      String(n)
        .split('')
        .reduce((total, value) => total + Number(value), 0)
    while (!fruits[num]) {
      num =
        num -
        String(num)
          .split('')
          .reduce((total, value) => total + Number(value), 0)
    }
    return fruits[num - 1]
  }